import turtle
turtle.Screen().bgcolor("yellow")
turtle.setup(400, 600)
turtle.title("This is the Turtle Window")
t = turtle.Turtle()
t.speed(5)
t.penup()
t.goto(-50, -50)
t.pendown()

t.fillcolor("white")
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()
t.penup()
t.goto(-30, 90)
t.pendown()

t.fillcolor("red")
t.begin_fill()
t.circle(30)
t.end_fill()
t.penup()
t.goto(-30, -150)
t.pendown()

t.fillcolor("black")
t.begin_fill()
t.circle(30)
t.end_fill()
t.hideturtle()
turtle.done()